valor = int(input("digite um numero para tabuada: "))
print(f"{valor} X {1:2} = {valor * 1}")
print(f"{valor} X {2:2} = {valor * 2}")
print(f"{valor} X {3:2} = {valor * 3}")
print(f"{valor} X {4:2} = {valor * 4}")
print(f"{valor} X {5:2} = {valor * 5}")
print(f"{valor} X {6:2} = {valor * 6}")
print(f"{valor} X {7:2} = {valor * 7}")
print(f"{valor} X {8:2} = {valor * 8}")
print(f"{valor} X {9:2} = {valor * 9}")
print(f"{valor} X {10:2} = {valor * 10}")
print("-" * 12)
