xablau = input("Digite Algo: ")
print(f"O tipo primitivo desse valor é {type(xablau)}")
print(f"Só tem espaços? {xablau.isspace()}")
print(f"É um numero? {xablau.isnumeric()}")
print(f"É alfabético? {xablau.isalpha()}")
print(f"É alfanumérico? {xablau.isalnum()}")
print(f"Está em maiúsculas? {xablau.isupper()}")
print(f"Está em minúsculas? {xablau.islower()}")
print(f"Está capitalizada? {bool(xablau.capitalize())}")
print(f"Está capitalizada? {xablau.istitle()}")
